### PR TITLE
Cypress testing/jedeo

### PR DESCRIPTION
**Pull request by Jedeo**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
This PR does tests for the `individual painting component"

## Type of change

- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)
- [ ] Refactor

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [ ] I tested my changes in the browser
- [x] I tested with cypress

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new bugs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Is your code D.R.Y?
- [ ] Does it follow SRP?

# Questions:
Are there any questions or concerns you want addressed in a code review?

# Next Steps:

### CODE REVIEW

**Review by Mlberry0205 — COMMENTED** [review]
Hey Jedeo, 

Fabulous work on the tests!  You covered a ton of user stories here! 
 I noticed there are a few extra spaces we can take out.  You will also want to make sure you are consistent with syntax.  Some of your tests have "cy" throughout the entire test and some don't.  I would choose one way or the other.

**Review by alyciacan — COMMENTED** [review]
All tests are passing!! Amazing work! Can you just update the test description where it still says 'empty spec'?

**Comment by Jedeo** [comment]
Thanks for the feedback on the Cypress test. I've made the changes requested

**Review by Mlberry0205 — APPROVED** [review]
Nice work, Jedeo!

**Pull request merged**
